@namespace
class SpriteKind:
    Sprite = SpriteKind.create()
    espectator = SpriteKind.create()
    Zombie_I = SpriteKind.create()
    cursor = SpriteKind.create()

def on_up_pressed():
    if Steve.vy == 0:
        Steve.vy = -100
controller.up.on_event(ControllerButtonEvent.PRESSED, on_up_pressed)

def on_b_pressed():
    if tiles.tile_at_location_equals(tiles.location_of_sprite(Cursor),
        assets.tile("""
            transparency16
        """)):
        music.play(music.create_sound_effect(WaveShape.TRIANGLE,
                300,
                200,
                255,
                0,
                75,
                SoundExpressionEffect.NONE,
                InterpolationCurve.CURVE),
            music.PlaybackMode.UNTIL_DONE)
        tiles.set_wall_at(tiles.location_of_sprite(Cursor), True)
        tiles.set_tile_at(tiles.location_of_sprite(Cursor),
            assets.tile("""
                myTile3
            """))
controller.B.on_event(ControllerButtonEvent.PRESSED, on_b_pressed)

def on_a_pressed():
    if tiles.tile_at_location_equals(tiles.location_of_sprite(Cursor),
        assets.tile("""
            myTile
        """)):
        music.play(music.create_sound_effect(WaveShape.SINE,
                1649,
                0,
                255,
                255,
                100,
                SoundExpressionEffect.NONE,
                InterpolationCurve.LINEAR),
            music.PlaybackMode.UNTIL_DONE)
        tiles.set_wall_at(tiles.location_of_sprite(Cursor), False)
        tiles.set_tile_at(tiles.location_of_sprite(Cursor),
            assets.tile("""
                transparency16
            """))
    if tiles.tile_at_location_equals(tiles.location_of_sprite(Cursor),
        assets.tile("""
            myTile5
        """)):
        music.play(music.create_sound_effect(WaveShape.SINE,
                1649,
                1,
                255,
                255,
                100,
                SoundExpressionEffect.NONE,
                InterpolationCurve.LINEAR),
            music.PlaybackMode.UNTIL_DONE)
        tiles.set_wall_at(tiles.location_of_sprite(Cursor), False)
        tiles.set_tile_at(tiles.location_of_sprite(Cursor),
            assets.tile("""
                transparency16
            """))
    if tiles.tile_at_location_equals(tiles.location_of_sprite(Cursor),
        assets.tile("""
            myTile3
        """)):
        music.play(music.create_sound_effect(WaveShape.SQUARE,
                672,
                300,
                255,
                255,
                100,
                SoundExpressionEffect.NONE,
                InterpolationCurve.LINEAR),
            music.PlaybackMode.UNTIL_DONE)
        tiles.set_wall_at(tiles.location_of_sprite(Cursor), False)
        tiles.set_tile_at(tiles.location_of_sprite(Cursor),
            assets.tile("""
                transparency16
            """))
    if tiles.tile_at_location_equals(tiles.location_of_sprite(Cursor),
        assets.tile("""
            myTile7
        """)):
        tiles.set_tile_at(tiles.location_of_sprite(Cursor),
            assets.tile("""
                transparency16
            """))
        tiles.set_wall_at(tiles.location_of_sprite(Cursor), False)
        music.play(music.create_sound_effect(WaveShape.SQUARE,
                1044,
                1,
                255,
                255,
                100,
                SoundExpressionEffect.NONE,
                InterpolationCurve.CURVE),
            music.PlaybackMode.UNTIL_DONE)
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

def on_left_pressed():
    global CursorX, CursorY
    Cursor.set_image(img("""
        . . . . d . . . . 
                . . . . d . . . . 
                . . . d d d . . . 
                . . d . . . d . . 
                d d d . . . d d d 
                . . d . . . d . . 
                . . . d d d . . . 
                . . . . d . . . . 
                . . . . d . . . .
    """))
    CursorX = -15
    CursorY = 5
    controller.move_sprite(Steve, 100, 0)
    animation.run_image_animation(Steve,
        [img("""
                ......88888777......
                        ......88888877......
                        ......8a99a9a7......
                        ......aa9aaaaa......
                        ......adc9acd9......
                        ......aaa8899a......
                        ......aa8668aa......
                        ......aa8888aa......
                        ........eeee........
                        .......eeeeee.......
                        ......aeeeeeea......
                        .....aaaeeeeea9.....
                        ....aaaaeeeeaaa9....
                        ...aaaaaeeaaa9aa9...
                        ...aaaaaeee999999...
                        ....aaa.eeee99a99...
                        .....a..eeee.9aa....
                        ........eeee........
                        ........cccc........
                        ........cccc........
                        ........ccccc.......
                        .......cccccc.......
                        .......ccccccc......
                        .......ccccccc......
                        ......ccccccccc.....
                        ......ccccccccc.....
                        .....cccccccccc.....
                        .....ccccc.ccccc....
                        .....ccccc.ccccc....
                        ....cccbb..cccccb...
                        ....cccbb...cccbb...
                        .....bbb.....bbb....
            """),
            img("""
                ......88888777......
                        ......88888877......
                        ......8a99a9a7......
                        ......aa9aaaaa......
                        ......adc9acd9......
                        ......aaa8899a......
                        ......aa8668aa......
                        ......aa8888aa......
                        ........eeee........
                        ........eeee........
                        ........eeee........
                        ........eeee........
                        ........aaaa........
                        ........99a9........
                        ........99a9........
                        ........99a9........
                        ........a9a9........
                        ........a9a9........
                        ........a999........
                        ........999a........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........ccbb........
                        ........bbbb........
                        ........bbbb........
            """),
            img("""
                ......88888777......
                        ......88888877......
                        ......8a99a9a7......
                        ......aa9aaaaa......
                        ......adc9acd9......
                        ......aaa8899a......
                        ......aa8668aa......
                        ......aa8888aa......
                        ........eeee........
                        .......eeeeee.......
                        ......aeeeeeea......
                        .....aaaeeeeea9.....
                        ....aaaaeeeeaaa9....
                        ...aaaaaeeaaa9aa9...
                        ...aaaaaeee999999...
                        ....aaa.eeee99a99...
                        .....a..eeee.9aa....
                        ........eeee........
                        ........cccc........
                        ........cccc........
                        ........ccccc.......
                        .......cccccc.......
                        .......ccccccc......
                        .......ccccccc......
                        ......ccccccccc.....
                        ......ccccccccc.....
                        .....cccccccccc.....
                        .....ccccc.ccccc....
                        .....ccccc.ccccc....
                        ....cccbb..cccccb...
                        ....cccbb...cccbb...
                        .....bbb.....bbb....
            """),
            img("""
                ......88888777......
                        ......88888877......
                        ......8a99a9a7......
                        ......aa9aaaaa......
                        ......adc9acd9......
                        ......aaa8899a......
                        ......aa8668aa......
                        ......aa8888aa......
                        ........eeee........
                        ........eeee........
                        ........eeee........
                        ........eeee........
                        ........aaaa........
                        ........99a9........
                        ........99a9........
                        ........99a9........
                        ........a9a9........
                        ........a9a9........
                        ........a999........
                        ........999a........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........ccbb........
                        ........bbbb........
                        ........bbbb........
            """)],
        190,
        True)
controller.left.on_event(ControllerButtonEvent.PRESSED, on_left_pressed)

def on_right_released():
    global CursorX, CursorY
    CursorX = 15
    CursorY = 5
    animation.run_image_animation(Steve,
        [img("""
            ......77788888......
                    ......77888888......
                    ......7a9a99a8......
                    ......aaaaa9aa......
                    ......9dca9cda......
                    ......a9988aaa......
                    ......aa8668aa......
                    ......aa8888aa......
                    ........eeee........
                    ........eeee........
                    ........eeee........
                    ........eeee........
                    ........aaaa........
                    ........9a99........
                    ........9a99........
                    ........9a99........
                    ........9a9a........
                    ........9a9a........
                    ........999a........
                    ........a999........
                    ........cccc........
                    ........cccc........
                    ........cccc........
                    ........cccc........
                    ........cccc........
                    ........cccc........
                    ........cccc........
                    ........cccc........
                    ........cccc........
                    ........bbcc........
                    ........bbbb........
                    ........bbbb........
        """)],
        190,
        True)
controller.right.on_event(ControllerButtonEvent.RELEASED, on_right_released)

def on_left_released():
    global CursorX, CursorY
    CursorX = -15
    CursorY = 5
    animation.run_image_animation(Steve,
        [img("""
            ......88888777......
                    ......88888877......
                    ......8a99a9a7......
                    ......aa9aaaaa......
                    ......adc9acd9......
                    ......aaa8899a......
                    ......aa8668aa......
                    ......aa8888aa......
                    ........eeee........
                    ........eeee........
                    ........eeee........
                    ........eeee........
                    ........aaaa........
                    ........99a9........
                    ........99a9........
                    ........99a9........
                    ........a9a9........
                    ........a9a9........
                    ........a999........
                    ........999a........
                    ........cccc........
                    ........cccc........
                    ........cccc........
                    ........cccc........
                    ........cccc........
                    ........cccc........
                    ........cccc........
                    ........cccc........
                    ........cccc........
                    ........ccbb........
                    ........bbbb........
                    ........bbbb........
        """)],
        190,
        True)
controller.left.on_event(ControllerButtonEvent.RELEASED, on_left_released)

def on_combos_attach_combo():
    pause(100)
    controller.move_sprite(Steve, 150, 0)
controller.combos.attach_combo("LL", on_combos_attach_combo)

def on_right_pressed():
    global CursorX, CursorY
    Cursor.set_image(img("""
        . . . . d . . . . 
                . . . . d . . . . 
                . . . d d d . . . 
                . . d . . . d . . 
                d d d . . . d d d 
                . . d . . . d . . 
                . . . d d d . . . 
                . . . . d . . . . 
                . . . . d . . . .
    """))
    CursorX = 15
    CursorY = 5
    controller.move_sprite(Steve, 100, 0)
    animation.run_image_animation(Steve,
        [img("""
                ......77788888......
                        ......77888888......
                        ......7a9a99a8......
                        ......aaaaa9aa......
                        ......9dca9cda......
                        ......a9988aaa......
                        ......aa8668aa......
                        ......aa8888aa......
                        ........eeee........
                        .......eeeeee.......
                        ......aeeeeeea......
                        .....9aeeeeeaaa.....
                        ....9aaaeeeeaaaa....
                        ...9aa9aaaeeaaaaa...
                        ...999999eeeaaaaa...
                        ...99a99eeee.aaa....
                        ....aa9.eeee..a.....
                        ........eeee........
                        ........cccc........
                        ........cccc........
                        .......ccccc........
                        .......cccccc.......
                        ......ccccccc.......
                        ......ccccccc.......
                        .....ccccccccc......
                        .....ccccccccc......
                        .....cccccccccc.....
                        ....ccccc.ccccc.....
                        ....ccccc.ccccc.....
                        ...bccccc..bbccc....
                        ...bbccc...bbccc....
                        ....bbb.....bbb.....
            """),
            img("""
                ......77788888......
                        ......77888888......
                        ......7a9a99a8......
                        ......aaaaa9aa......
                        ......9dca9cda......
                        ......a9988aaa......
                        ......aa8668aa......
                        ......aa8888aa......
                        ........eeee........
                        ........eeee........
                        ........eeee........
                        ........eeee........
                        ........aaaa........
                        ........9a99........
                        ........9a99........
                        ........9a99........
                        ........9a9a........
                        ........9a9a........
                        ........999a........
                        ........a999........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........bbcc........
                        ........bbbb........
                        ........bbbb........
            """),
            img("""
                ......77788888......
                        ......77888888......
                        ......7a9a99a8......
                        ......aaaaa9aa......
                        ......9dca9cda......
                        ......a9988aaa......
                        ......aa8668aa......
                        ......aa8888aa......
                        ........eeee........
                        .......eeeeee.......
                        ......aeeeeeea......
                        .....9aeeeeeaaa.....
                        ....9aaaeeeeaaaa....
                        ...9aa9aaaeeaaaaa...
                        ...999999eeeaaaaa...
                        ...99a99eeee.aaa....
                        ....aa9.eeee..a.....
                        ........eeee........
                        ........cccc........
                        ........cccc........
                        .......ccccc........
                        .......cccccc.......
                        ......ccccccc.......
                        ......ccccccc.......
                        .....ccccccccc......
                        .....ccccccccc......
                        .....cccccccccc.....
                        ....ccccc.ccccc.....
                        ....ccccc.ccccc.....
                        ...bccccc..bbccc....
                        ...bbccc...bbccc....
                        ....bbb.....bbb.....
            """),
            img("""
                ......77788888......
                        ......77888888......
                        ......7a9a99a8......
                        ......aaaaa9aa......
                        ......9dca9cda......
                        ......a9988aaa......
                        ......aa8668aa......
                        ......aa8888aa......
                        ........eeee........
                        ........eeee........
                        ........eeee........
                        ........eeee........
                        ........aaaa........
                        ........9a99........
                        ........9a99........
                        ........9a99........
                        ........9a9a........
                        ........9a9a........
                        ........999a........
                        ........a999........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........cccc........
                        ........bbcc........
                        ........bbbb........
                        ........bbbb........
            """)],
        190,
        True)
controller.right.on_event(ControllerButtonEvent.PRESSED, on_right_pressed)

def on_combos_attach_combo2():
    pause(100)
    controller.move_sprite(Steve, 150, 0)
controller.combos.attach_combo("RR", on_combos_attach_combo2)

def on_down_pressed():
    global CursorX, CursorY
    CursorX = 0
    CursorY = 25
controller.down.on_event(ControllerButtonEvent.PRESSED, on_down_pressed)

def on_menu_pressed():
    global CursorX, CursorY
    Cursor.set_image(img("""
        . . . . d . . . . 
                . . . . d . . . . 
                . . . d d d . . . 
                . . d . . . d . . 
                d d d . . . d d d 
                . . d . . . d . . 
                . . . d d d . . . 
                . . . . d . . . . 
                . . . . d . . . .
    """))
    CursorX = 0
    CursorY = -25
controller.menu.on_event(ControllerButtonEvent.PRESSED, on_menu_pressed)

def CreateNewWorld():
    global LandHight
    LandHight = 8
    for XIndex in range(32):
        if Math.percent_chance(HillHightRange / 2):
            LandHight = LandHight - 1
        if Math.percent_chance(HillHightRange / 2):
            LandHight = LandHight - 1
        if Math.percent_chance(HillHightRange / 2):
            LandHight = LandHight + 1
        if Math.percent_chance(HillHightRange / 2):
            LandHight = LandHight + 1
        tiles.set_tile_at(tiles.get_tile_location(XIndex, LandHight),
            assets.tile("""
                myTile
            """))
        tiles.set_wall_at(tiles.get_tile_location(XIndex, LandHight), True)
        YIndex = 0
        while YIndex <= 31 - LandHight:
            tiles.set_tile_at(tiles.get_tile_location(XIndex, 32 - YIndex),
                assets.tile("""
                    myTile5
                """))
            tiles.set_wall_at(tiles.get_tile_location(XIndex, 32 - YIndex), True)
            YIndex += 1
        YIndex3 = 0
        while YIndex3 <= 31 - LandHight:
            tiles.set_tile_at(tiles.get_tile_location(XIndex, 33 - YIndex3),
                assets.tile("""
                    myTile7
                """))
            tiles.set_wall_at(tiles.get_tile_location(XIndex, 32 - YIndex3), True)
            YIndex3 += 1
        YIndex2 = 0
        while YIndex2 <= 31 - LandHight:
            tiles.set_tile_at(tiles.get_tile_location(XIndex, 45 - YIndex2),
                assets.tile("""
                    myTile7
                """))
            tiles.set_wall_at(tiles.get_tile_location(XIndex, 32 - YIndex2), True)
            YIndex2 += 1
        YIndex22 = 0
        while YIndex22 <= 31 - LandHight:
            tiles.set_tile_at(tiles.get_tile_location(XIndex, 51 - YIndex22),
                assets.tile("""
                    myTile1
                """))
            tiles.set_wall_at(tiles.get_tile_location(XIndex, 32 - YIndex22), True)
            YIndex22 += 1
LandHight = 0
CursorY = 0
CursorX = 0
Cursor: Sprite = None
Steve: Sprite = None
HillHightRange = 0
# From 0 to 100. The higher the number, the bumpier the terrain. 0 means a superflatworld.
HillHightRange = 10
tiles.set_current_tilemap(tilemap("""
    level3
"""))
CreateNewWorld()
scene.set_background_color(15)
Steve = sprites.create(assets.image("""
    STEVE
"""), SpriteKind.player)
sprites.set_data_image_value(Steve, "Steve", assets.image("""
    STEVE
"""))
scene.camera_follow_sprite(Steve)
controller.move_sprite(Steve, 100, 0)
Steve.ay = 300
tiles.place_on_tile(Steve, tiles.get_tile_location(1, 2))
Cursor = sprites.create(img("""
        . . . . d . . . . 
            . . . . d . . . . 
            . . . d d d . . . 
            . . d . . . d . . 
            d d d . . . d d d 
            . . d . . . d . . 
            . . . d d d . . . 
            . . . . d . . . . 
            . . . . d . . . .
    """),
    SpriteKind.cursor)
Cursor.set_flag(SpriteFlag.STAY_IN_SCREEN, True)
Cursor.set_flag(SpriteFlag.GHOST, True)
CursorX = 15
CursorY = 5

def on_on_update():
    global CursorX, CursorY
    if True:
        CursorX += -1
    if True:
        CursorX += 1
    if True:
        CursorY += -1
    if True:
        CursorY += 1
    Cursor.set_position(scene.camera_property(CameraProperty.X) + CursorX,
        scene.camera_property(CameraProperty.Y) + CursorY)
game.on_update(on_on_update)
